BadgerBoysWebApp/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BadgerBoysWebApp.Models
{
    public class Booking
    {
        public string Name { get; set; }
        public string Email { get; set; }

        [Display(Name = "Event Date")]
        public DateTime Date { get; set; }
        public string Description { get; set; }
    }
}

BadgerBoysWebApp/Models/Gig.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BadgerBoysWebApp.Models
{
    public class Gig
    {
        public string Location { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public int Index { get; set; }
    }
}

BadgerBoysWebApp/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BadgerBoysWebApp.Models
{
    public class Login
    {
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

BadgerBoysWebApp/Models/Testimonial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BadgerBoysWebApp.Models
{
    public class Testimonial
    {
        public int Index { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
    }
}

BadgerBoysWebApp/Controllers/BadgersOnlyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BadgerBoysWebApp.Data;
using BadgerBoysWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BadgerBoysWebApp.Controllers
{
    public class BadgersOnlyController : Controller
    {
        private static List<Testimonial> _Testimonials = DataAccess.GetAllTestimonials();
        private static List<Gig> _Gigs = DataAccess.GetAllGigs();

        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult ListTestimonials()
        {
            _Testimonials = DataAccess.GetAllTestimonials();
            return View(_Testimonials);
        }

        public IActionResult EditTestimonial(int index)
        {
            return View(_Testimonials[index]);
        }

        [HttpPost]
        public IActionResult EditTestimonial(Testimonial testimonial)
        {
            _Testimonials[testimonial.Index] = testimonial;
            DataAccess.SaveAllTestimonials(_Testimonials);
            return RedirectToAction("ListTestimonials");
        }

        public IActionResult AddTestimonial()
        {
            _Testimonials = DataAccess.GetAllTestimonials();
            _Testimonials.Insert(0, new Testimonial());
            return RedirectToAction("EditTestimonial", new { index = 0 });
        }

        public IActionResult DeleteTestimonial(int index)
        {
            _Testimonials.RemoveAt(index);
            DataAccess.SaveAllTestimonials(_Testimonials);
            return RedirectToAction("ListTestimonials");
        }

        public IActionResult MoveTestimonialUp(int index)
        {
            if (index != 0)
            {
                var toMove = _Testimonials[index];
                _Testimonials.RemoveAt(index);
                _Testimonials.Insert(index - 1, toMove);
                DataAccess.SaveAllTestimonials(_Testimonials);
            }
            return RedirectToAction("ListTestimonials");
        }

        public IActionResult MoveTestimonialDown(int index)
        {
            if (index < _Testimonials.Count - 1)
            {
                var toMove = _Testimonials[index];
                _Testimonials.RemoveAt(index);
                _Testimonials.Insert(index + 1, toMove);
                DataAccess.SaveAllTestimonials(_Testimonials);
            }
            return RedirectToAction("ListTestimonials");
        }

        public IActionResult ListGigs()
        {
            _Gigs = DataAccess.GetAllGigs();
            return View(_Gigs);
        }

        public IActionResult AddGig()
        {
            _Gigs.Insert(0, new Gig());
            return RedirectToAction("EditGig", new { index = 0 });
        }

        public IActionResult EditGig(int index)
        {
            return View(_Gigs[index]);
        }

        [HttpPost]
        public IActionResult EditGig(Gig gig)
        {
            _Gigs[gig.Index] = gig;
            DataAccess.SaveAllGigs(_Gigs
                .OrderByDescending(g => g.Date)
                .ToList());
            return RedirectToAction("ListGigs");
        }

        public IActionResult DeleteGig(int index)
        {
            _Gigs.RemoveAt(index);
            DataAccess.SaveAllGigs(_Gigs);
            return RedirectToAction("ListGigs");
        }
    }
}

BadgerBoysWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using BadgerBoysWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using BadgerBoysWebApp.Data;
using System.Net.Mail;

namespace BadgerBoysWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Gigs()
        {
            return View(
                DataAccess.GetAllGigs()
                .Where(g => g.Date > DateTime.Now)
                .OrderBy(g => g.Date));
        }

        public IActionResult Testimonials()
        {
            return View(DataAccess.GetAllTestimonials());
        }

        public IActionResult Media()
        {
            return View();
        }

        public IActionResult Contact()
        {
            var booking = new Booking
            {
                Date = DateTime.Now.Date
            };
            return View("Contact", model: booking);
        }

        public IActionResult SubmitBooking(Booking booking)
        {
            SmtpClient client = new SmtpClient();
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.EnableSsl = true;
            client.Host = "smtp.sendgrid.net";
            client.Port = 587;

            // setup Smtp authentication
            System.Net.NetworkCredential credentials =
                new System.Net.NetworkCredential(DataAccess.EmailUser(), DataAccess.EmailPassword());
            client.UseDefaultCredentials = false;
            client.Credentials = credentials;

            
            try
            {
                MailMessage msg = new MailMessage();
                msg.From = new MailAddress("badgerboysband@gmail.com");
                msg.To.Add(new MailAddress(booking.Email));
                msg.CC.Add(new MailAddress("badgerboysband@gmail.com"));

                msg.Subject = "Badger Boys Booking: " + booking.Date.ToShortDateString();
                msg.IsBodyHtml = true;
                msg.Body = string.Format("<p>Thank you for contacting us! </p> <p>We have received your request for the following event...</p> <p>Date: {0}</p> <p>Description: {1}</p> <p> We will contact you shortly with our availability and a quote.</p> <p>Best Wishes,</p> <p>Badger Boys</p>", booking.Date, booking.Description);
                client.Send(msg);

                
                ViewBag.Message = "Thank you! We will be in touch shortly";
            }
            catch (FormatException ex)
            {
                ViewBag.Message = "Error occured while sending your message. are you sure you've entered a valid email?" + ex.Message;
            }
            catch (Exception ex)
            { 
                ViewBag.Message = "Error occured while sending your message. " + ex.Message;
            }

            
            return View("Contact");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

BadgerBoysWebApp/Views/BadgersOnly/EditGig.cshtml
@model BadgerBoysWebApp.Models.Gig

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Gig</h2>

<h4>Gig</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditGig">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Index" class="control-label"></label>
                <p>@Model.Index</p>
                @Html.HiddenFor(g => g.Index)
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListGigs">Back to List</a>
</div>

BadgerBoysWebApp/Views/BadgersOnly/EditTestimonial.cshtml
@model BadgerBoysWebApp.Models.Testimonial

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Testimonial</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditTestimonial">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Index" class="control-label"></label>
                <p>@Model.Index</p>
                @Html.HiddenFor(t => t.Index)
                
                <span asp-validation-for="Index" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control" id="testimonial-content"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListTestimonials">Back to List</a>
</div>

BadgerBoysWebApp/Views/BadgersOnly/Index.cshtml
@{
    ViewData["Title"] = "Badgers Only";
}

<h2>What would you like to edit?</h2>
<ul>
    <li><a asp-area="" asp-controller="BadgersOnly" asp-action="ListTestimonials">Testimonials</a></li>
    <li><a asp-area="" asp-controller="BadgersOnly" asp-action="ListGigs">Gigs</a></li>
</ul>

BadgerBoysWebApp/Views/BadgersOnly/ListGigs.cshtml
@model IEnumerable<BadgerBoysWebApp.Models.Gig>

@{
    ViewData["Title"] = "Gigs";
}

<h2>All Gigs</h2>

<p>
    <a asp-action="AddGig">Add New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Location)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Link)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Link)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditGig", new { index = item.Index }) |
                @Html.ActionLink("Delete", "DeleteGig", new { index = item.Index })
            </td>
        </tr>
}
    </tbody>
</table>

BadgerBoysWebApp/Views/BadgersOnly/ListTestimonials.cshtml
@model IEnumerable<BadgerBoysWebApp.Models.Testimonial>

@{
    ViewData["Title"] = "List Testimonials";
}

<h2>All Testimonials</h2>
<hr />
<p>
    <a asp-action="AddTestimonial">Add New</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
                <th class="col-md-2">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th class="col-md-8">
                    @Html.DisplayNameFor(model => model.Content)
                </th>
            <th class="col-md-2">Modify</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditTestimonial", new { index = item.Index }) |
                @Html.ActionLink("Delete", "DeleteTestimonial", new { index = item.Index }) |
                @Html.ActionLink("Up", "MoveTestimonialUp", new { index = item.Index }) |
                @Html.ActionLink("Down", "MoveTestimonialDown", new { index = item.Index })
            </td>
        </tr>
}
    </tbody>
</table>

BadgerBoysWebApp/Views/BadgersOnly/Login.cshtml
@model BadgerBoysWebApp.Models.Login

@{
    ViewData["Title"] = "Login";
}

<h2>Badgers Only</h2>

<h4>Login</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div>
                <p class="text-danger">@ViewBag.Error</p>
            </div>
            <div class="form-group">
                <input type="submit" value="Log in" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BadgerBoysWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h5>Choose a badger to see their bio...</h5>

<div id="bio-images" class="container text-center">
    <div class="row">
        <div class="col-md-6 col-lg-4">
            <img src="~/images/mattBadger.jpg" class="badger-boy" id="matt-badger"/>
        </div>
        <div class="col-md-6 col-lg-4">
            <img src="~/images/alexBadger.jpg" class="badger-boy" id="alex-badger"/>
        </div>
        <div class="col-md-12 col-lg-4">
            <img src="~/images/tommieBadger.jpg" class="badger-boy" id="tommie-badger"/>
        </div>
    </div>
</div>


<div id="bio-holder" class="container">
    <hr/>
    <div id="matt-bio" class="row" style="display: none">
        <div class="bio-photo col-xl-4 col-lg-5 col-md-6 text-center" >
            <img src="~/images/mattDerp.jpg" />
        </div>
        <div class="bio-text col-xl-8 col-lg-7 col-md-6">
            <h2>Matt.</h2>
            <p>
                As the other front man Matt plays guitar and adds vocals to Alex’s lead. He says that ‘the best thing about being a Badger Boy is seeing the response of the crowd to the music we play’ and loves performing in as many places as possible!
                Matt also enjoys making a wide variety of music seem fresh, with only three badgers meaning the approach to songs must be unique. With mistakes and a lack of talent being his strengths, you’ll never hear the songs played in the same way again!!
            </p>
        </div>
    </div>
    <div id="alex-bio" class="row" style="display: none">
        <div class="bio-photo col-xl-4 col-lg-5 col-md-6 text-center">
            <img src="~/images/alexLegend.jpg" />
        </div>
        <div class="bio-text col-xl-8 col-lg-7 col-md-6">
            <h2>Alex.</h2>
            <p>
                Alex is a legend.
            </p>
        </div>
    </div>
    <div id="tommie-bio" class="row" style="display: none"></div>
</div>

BadgerBoysWebApp/Views/Home/Contact.cshtml
@model BadgerBoysWebApp.Models.Booking
@{
    ViewData["Title"] = "Contact";
}
<h2>Contact Us.</h2>
<hr />
<h3>Booking Form</h3>

<form asp-action="SubmitBooking">

    <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" >
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <input type="submit" value="Send" class="btn btn-success" />
                    <p>@ViewBag.Message</p>
                </div>
            </div>
        </div>

</form>

<hr />
<address>
    <p><strong>Email: </strong> <a href="mailto:badgerboysband@gmail.com">badgerboysband@gmail.com</a><br /></p>
    <p><strong>Phone Alex: </strong> <a href="tel:+447490413335">07490 413335</a></p>
    <p><strong>Phone Matt: </strong> <a href="tel:+4407900380799">07900 380799</a></p>
</address>

BadgerBoysWebApp/Views/Home/Gigs.cshtml
@model IEnumerable<BadgerBoysWebApp.Models.Gig>

@{
    ViewData["Title"] = "Gigs";
}

<h2>Upcoming Gigs.</h2>

<hr />

<div class="container">
    <div class="row headings d-none d-md-flex">
        <div class="col-md-2 gig-item-detail">
            <b>@Html.DisplayNameFor(model => model.Location)</b>
        </div>
        <div class="col-md-2 gig-item-detail">
            <b>@Html.DisplayNameFor(model => model.Date)</b>
        </div>
        <div class="col-md-4 gig-item-detail">
            <b>@Html.DisplayNameFor(model => model.Description)</b>
        </div>
        <div class="col-md-4 gig-item-detail">
            <b>@Html.DisplayNameFor(model => model.Link)</b>
        </div>

    </div>
    <hr class="d-none d-md-flex" />
    @foreach (var item in Model)
    {
    <div class="row gig-item">
        <div class="col-md-2 gig-item-detail">
            <b>@Html.DisplayFor(modelItem => item.Location) </b>
        </div>
        <div class="col-md-2 gig-item-detail">
            @item.Date.ToLongDateString()
        </div>
        <div class="col-md-4 gig-item-detail">
            @Html.DisplayFor(modelItem => item.Description)
        </div>
        <div class="col-md-4 gig-item-detail">
            @Html.DisplayFor(modelItem => item.Link)
        </div>
    </div>
    }
</div>

BadgerBoysWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

@section Scripts {
    <!-- SCRIPT DECLARATIONS GO HERE -->
}

<div id="home-page">
    <div id="index-intro">
        <div class="d-none d-lg-block d-md-block">
            <h1 id="title-text-large">BADGER BOYS</h1>
        </div>
        <div class="d-md-none">
            <h1 id="title-text-small">BADGER BOYS</h1>
        </div>
        <h2>Welcome.</h2>
        <p>
            Welcome to the home of Badger Boys Band.
            A local Dorset based covers band touring pubs, parties and festivals!
        </p>
    </div>
    <div>
        <iframe class="facebook-vid" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fthebadgerboys%2Fvideos%2F1561250167330785%2F&show_text=0" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>
    </div>
    <h2>About.</h2>
    <h5>Choose a badger to see their bio...</h5>

    <div id="bio-images" class="container text-center">
        <div class="row">
            <div class="col-4">
                <img src="~/images/mattBadger.png" class="badger-boy" id="matt-badger" />
            </div>
            <div class="col-4">
                <img src="~/images/alexBadger.png" class="badger-boy" id="alex-badger" />
            </div>
            <div class="col-4">
                <img src="~/images/tommieBadger.png" class="badger-boy" id="tommie-badger" />
            </div>
        </div>
    </div>


    <div id="bio-holder" class="container">
        <hr />
        <div id="matt-bio" class="row" style="display: none">
            <div class="bio-photo col-xl-4 col-lg-5 col-md-6 text-center">
                <img src="~/images/matty.jpg" />
            </div>
            <div class="bio-text col-xl-8 col-lg-7 col-md-6">
                <h2>Matt.</h2>
                <p>
                    As one of the front badgers Matt plays guitar and provides vocals. He says that ‘the best thing about being a Badger Boy is seeing the response of the crowd to the music we play’ and loves performing in as many places as possible!
                    Matt also enjoys making a wide variety of music seem fresh, with only three badgers meaning the approach to songs must be unique. Don't let this badger play himself down, he really is the bees (badgers) knees, you’ll never hear the songs played in the same way again!!
                </p>
            </div>
        </div>
        <div id="alex-bio" class="row" style="display: none">
            <div class="bio-photo col-xl-4 col-lg-5 col-md-6 text-center">
                <img src="~/images/alexLegend.jpg" />
            </div>
            <div class="bio-text col-xl-8 col-lg-7 col-md-6">
                <h2>Alex.</h2>
                <p>
                    Alex is the curly badger of the group. Curly in hair and curly in comments, don't let this badger's terrible chat put you off though, he often scratches out the odd bass solo and will occasionally attempt to play the keyboard.
                    Alex loves all kinds of music, and seeing an audience on their feet makes this badger very happy indeed.
                </p>
            </div>
        </div>
        <div id="tommie-bio" class="row" style="display: none">
            <div class="bio-photo col-xl-4 col-lg-5 col-md-6 text-center">
                <img src="~/images/tommie.jpg" />
            </div>
            <div class="bio-text col-xl-8 col-lg-7 col-md-6">
                <h2>Tommie.</h2>
                <p>
                    Being the youngest of the group drummer Tommie is still looked upon as the "Baby Badger" but that does not show with his attitude to playing what so ever!. This badgerling offers such a refreshing, unique and solid style to their repertoire. Thinking of new creative ideas to play all the time he's normally known as the "loud one" and thats just off stage.. He thrives off seeing people dance and enjoy the wide array of music they play. So no matter what be sure to get your dancing paws on at every gig!!
                </p>
            </div>
        </div>
    </div>
</div>

BadgerBoysWebApp/Views/Home/Media.cshtml
@{
    ViewData["Title"] = "Media";
}

<h2 class="text-center">Photos.</h2>
<hr />
<div id="photoCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#photoCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#photoCarousel" data-slide-to="1"></li>
        <li data-target="#photoCarousel" data-slide-to="2"></li>
        <li data-target="#photoCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/images/crowd.JPG" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/alexnmatt.JPG" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/drums.jpg" alt="Third slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/tommiewide.JPG" alt="Fourth slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#photoCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#photoCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="text-center mt-5 mb-5">
    <iframe class="facebook-vid" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FTheBearInnWincanton%2Fvideos%2F459449837923390%2F&show_text=0&width=560" width="560" height="315" style="border:10p;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>
    <iframe class="facebook-vid" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fthebadgerboys%2Fvideos%2F1512650122190790%2F&show_text=0&width=560" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>
</div>

BadgerBoysWebApp/Views/Home/Testimonials.cshtml
@model List<BadgerBoysWebApp.Models.Testimonial>
@{
    ViewData["Title"] = "Testimonials";
}

<h2>Feedback.</h2>
<hr />
<p>Many of the reviews below refer to us under our former name "The Threetles".</p>
<div class="container-fluid">
    <div class="row">
        @foreach (var item in Model)
        {
            @if (item.Index % 2 == 0)
            {
                <div class="col-md-4" id="testimonial-holder-1">
                    <p>@item.Name</p>
                    <p>@item.Content</p>
                </div>
            }
            else
            {
                <div class="col-md-4" id="testimonial-holder-2">
                    <p>@item.Name</p>
                    <p>@item.Content</p>
                </div>
            }

        }
    </div>
</div>